/-
Copyright (c) 2026 Ezzeri Esa. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.MeasureTheory.Function.ConvergenceInDistribution
import Mathlib.MeasureTheory.Function.Holder
import Mathlib.MeasureTheory.Measure.LevyConvergence
import Mathlib.MeasureTheory.Measure.LogLikelihoodRatio
import Mathlib.MeasureTheory.Measure.SeparableMeasure
import Mathlib.Analysis.InnerProductSpace.l2Space
import Mathlib.Probability.BrownianMotion.Basic
import Mathlib.Probability.Distributions.Gaussian.Fernique
import Mathlib.Probability.Distributions.Gaussian.HasGaussianLaw.Basic
import Mathlib.Probability.Moments.CovarianceBilinDual
import Mathlib.Probability.Process.Predictable
/-!
# Malliavin calculus through the Clark--Ocone formula

This statement gives explicit Mathlib-only meanings to the Cameron--Martin
space, the smooth Malliavin derivative, its graph closure, predictable
projection, and the natural predictable process space.  The theorem supplies
the time realization and Brownian Itô isometry and states martingale
representation together with the Clark--Ocone identity on the closed graph.
-/
open MeasureTheory ProbabilityTheory Filter Topology
open scoped ENNReal NNReal Real Topology InnerProductSpace
noncomputable section
namespace PalomarClarkOcone

universe u

/-- Lebesgue measure on nonnegative time. -/
noncomputable def nonnegativeLebesgueMeasure : Measure ℝ≥0 :=
  Measure.comap ((↑) : ℝ≥0 → ℝ) (volume : Measure ℝ)

/-- Square-integrable real random variables. -/
abbrev RandomL2 {W : Type u} [MeasurableSpace W] (P : Measure W) := Lp ℝ 2 P

/-- Square-integrable real processes on time times sample space. -/
abbrev TimeProcessL2 {W : Type u} [MeasurableSpace W] (P : Measure W) :=
  Lp ℝ 2 (nonnegativeLebesgueMeasure.prod P)

/-- Predictable square-integrable processes. -/
noncomputable abbrev PredictableProcessL2
    {W : Type u} [MeasurableSpace W]
    (filtration : Filtration ℝ≥0 ‹MeasurableSpace W›) (P : Measure W) :=
  lpMeas ℝ ℝ filtration.predictable 2 (nonnegativeLebesgueMeasure.prod P)

/-- The measurable space generated by a process's coordinates. -/
abbrev processMeasurableSpace {W : Type u} (B : ℝ≥0 → W → ℝ) : MeasurableSpace W :=
  ⨆ t : ℝ≥0, MeasurableSpace.comap (B t) (borel ℝ)

/-- The process coordinates generate the ambient measurable space. -/
def IsWienerGenerated {W : Type u} [MeasurableSpace W] (B : ℝ≥0 → W → ℝ) : Prop :=
  processMeasurableSpace B = ‹MeasurableSpace W›

/-- The constant `L²` representative of a random variable's expectation. -/
noncomputable def expectationL2
    {W : Type u} [MeasurableSpace W] {P : Measure W} [IsFiniteMeasure P]
    (G : RandomL2 P) : RandomL2 P :=
  Lp.const 2 P (∫ w, G w ∂P)

/-- The Cameron--Martin Hilbert space. -/
noncomputable def CameronMartin.Space
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    (P : Measure W) [IsGaussian P] : Submodule ℝ (Lp ℝ 2 P) :=
  (StrongDual.toLp P 2 -
    (Lp.constL 2 P ℝ).comp
      (ContinuousLinearMap.apply ℝ ℝ (∫ x, x ∂P))).range.topologicalClosure

namespace CameronMartin

/-- The identity random variable centered by its Bochner mean. -/
noncomputable def centeredId
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    (P : Measure W) [IsGaussian P] : W → W :=
  id - fun _ ↦ ∫ x, x ∂P

/-- The centered identity is square-integrable. -/
theorem memLp_centeredId
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    (P : Measure W) [IsGaussian P] : MemLp (centeredId P) 2 P := by
  exact (IsGaussian.memLp_id P 2 (by norm_num)).sub (memLp_const (∫ x, x ∂P))

/-- The centered identity in `L²(P; W)`. -/
noncomputable def centeredIdLp
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    (P : Measure W) [IsGaussian P] : Lp W 2 P :=
  (memLp_centeredId P).toLp (centeredId P)

/-- The Gaussian covariance map. -/
noncomputable def covarianceMap
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    (P : Measure W) [IsGaussian P] : Lp ℝ 2 P →L[ℝ] W :=
  ((ContinuousLinearMap.lsmul ℝ ℝ (E := W)).lpPairing P 2 2).flip (centeredIdLp P)

/-- The covariance embedding of Cameron--Martin directions into `W`. -/
noncomputable def inclusion
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    (P : Measure W) [IsGaussian P] : Space P →L[ℝ] W :=
  (covarianceMap P).domRestrict (Space P)

/-- A continuous linear functional as its centered Cameron--Martin class. -/
noncomputable def ofDual
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    (P : Measure W) [IsGaussian P] : StrongDual ℝ W →L[ℝ] Space P :=
  (StrongDual.toLp P 2 - (Lp.constL 2 P ℝ).comp
    (ContinuousLinearMap.apply ℝ ℝ (∫ x, x ∂P))).codRestrict (Space P)
      fun L ↦ Submodule.le_topologicalClosure _ ⟨L, rfl⟩

instance instCompleteSpaceSpace
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    (P : Measure W) [IsGaussian P] : CompleteSpace (Space P) :=
  inferInstanceAs (CompleteSpace
    ((StrongDual.toLp P 2 -
      (Lp.constL 2 P ℝ).comp
        (ContinuousLinearMap.apply ℝ ℝ (∫ x, x ∂P))).range.topologicalClosure))

end CameronMartin

/-- The smooth Malliavin derivative in Cameron--Martin directions. -/
noncomputable def mderiv
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    (P : Measure W) [IsGaussian P] (F : W → ℝ) (x : W) : CameronMartin.Space P :=
  (InnerProductSpace.toDual ℝ (CameronMartin.Space P)).symm
    ((fderiv ℝ F x).comp (CameronMartin.inclusion P))

/-- The rank-one `H`-valued random variable `w ↦ G(w)h`. -/
noncomputable def smulLp
    {W E : Type u} [MeasurableSpace W]
    [NormedAddCommGroup E] [NormedSpace ℝ E] {P : Measure W}
    (h : E) : RandomL2 P →L[ℝ] Lp E 2 P :=
  (ContinuousLinearMap.toSpanSingleton ℝ h).compLpL 2 P

/-- Bounded `C¹` functionals with uniformly bounded derivative. -/
structure IsSmoothBounded
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W] (F : W → ℝ) : Prop where
  contDiff : ContDiff ℝ 1 F
  bounded : ∃ C, ∀ x, |F x| ≤ C
  bounded_fderiv : ∃ C, ∀ x, ‖fderiv ℝ F x‖ ≤ C

namespace IsSmoothBounded

theorem continuous_fderiv
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    {F : W → ℝ} (hF : IsSmoothBounded F) : Continuous (fderiv ℝ F) :=
  hF.contDiff.continuous_fderiv one_ne_zero

theorem memLp
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [MeasurableSpace W] [BorelSpace W]
    {F : W → ℝ} (P : Measure W) [IsGaussian P]
    (hF : IsSmoothBounded F) (p : ℝ≥0∞) : MemLp F p P := by
  obtain ⟨C, hC⟩ := hF.bounded
  exact MemLp.of_bound hF.contDiff.continuous.aestronglyMeasurable C
    (Filter.Eventually.of_forall fun x ↦ by simpa [Real.norm_eq_abs] using hC x)

theorem continuous_mderiv
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    {F : W → ℝ} (P : Measure W) [IsGaussian P]
    (hF : IsSmoothBounded F) : Continuous (mderiv P F) := by
  unfold mderiv
  exact (InnerProductSpace.toDual ℝ (CameronMartin.Space P)).symm.continuous.comp
    (hF.continuous_fderiv.clm_comp continuous_const)

theorem exists_norm_mderiv_le
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    {F : W → ℝ} (P : Measure W) [IsGaussian P]
    (hF : IsSmoothBounded F) : ∃ C, ∀ x, ‖mderiv P F x‖ ≤ C := by
  obtain ⟨C, hC⟩ := hF.bounded_fderiv
  refine ⟨C * ‖CameronMartin.inclusion P‖, fun x ↦ ?_⟩
  unfold mderiv
  rw [LinearIsometryEquiv.norm_map]
  exact (ContinuousLinearMap.opNorm_comp_le _ _).trans
    (mul_le_mul_of_nonneg_right (hC x) (ContinuousLinearMap.opNorm_nonneg _))

theorem memLp_mderiv
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    {F : W → ℝ} (P : Measure W) [IsGaussian P]
    (hF : IsSmoothBounded F) (p : ℝ≥0∞) : MemLp (mderiv P F) p P := by
  obtain ⟨C, hC⟩ := hF.exists_norm_mderiv_le P
  exact MemLp.of_bound (hF.continuous_mderiv P).aestronglyMeasurable C
    (Filter.Eventually.of_forall hC)

/-- A smooth functional as a scalar `L²` class. -/
noncomputable def toLp
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    {F : W → ℝ} (P : Measure W) [IsGaussian P]
    (hF : IsSmoothBounded F) : Lp ℝ 2 P :=
  (hF.memLp P 2).toLp F

/-- The smooth Malliavin derivative as an `L²(P; H)` class. -/
noncomputable def mderivLp
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    {F : W → ℝ} (P : Measure W) [IsGaussian P]
    (hF : IsSmoothBounded F) : Lp (CameronMartin.Space P) 2 P :=
  (hF.memLp_mderiv P 2).toLp (mderiv P F)

end IsSmoothBounded

/-- `(F, η)` belongs to the closure of the smooth Malliavin graph. -/
def InGraphClosure
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    (P : Measure W) [IsGaussian P]
    (F : Lp ℝ 2 P) (η : Lp (CameronMartin.Space P) 2 P) : Prop :=
  ∃ Fk : ℕ → {f : W → ℝ // IsSmoothBounded f},
    Tendsto (fun k ↦ (Fk k).2.toLp P) atTop (𝓝 F) ∧
      Tendsto (fun k ↦ (Fk k).2.mderivLp P) atTop (𝓝 η)

/-- The predictable sigma-algebra lies below the ambient product sigma-algebra. -/
theorem predictable_le_prod
    {W : Type u} [MeasurableSpace W]
    (filtration : Filtration ℝ≥0 ‹MeasurableSpace W›) :
    filtration.predictable ≤ (inferInstance : MeasurableSpace (ℝ≥0 × W)) := by
  apply measurableSpace_le_predictable_of_measurableSet
  · intro A hA
    exact (measurableSet_singleton (0 : ℝ≥0)).prod (filtration.le 0 A hA)
  · intro t A hA
    exact measurableSet_Ioi.prod (filtration.le t A hA)

/-- Orthogonal projection onto predictable processes. -/
noncomputable def predictableProjection
    {W : Type u} [MeasurableSpace W] {P : Measure W}
    (filtration : Filtration ℝ≥0 ‹MeasurableSpace W›) :
    TimeProcessL2 P →L[ℝ] PredictableProcessL2 filtration P :=
  condExpL2 ℝ ℝ (predictable_le_prod filtration)

/-- **Generated-space martingale representation and textbook Clark--Ocone.** There are
a time realization of the closed Malliavin derivative and a Brownian Itô
isometry such that every terminal `L²` variable has a stochastic-integral
representation. For every pair in the closed Malliavin graph, the predictable
projection of the derivative has a representative whose time sections are the
conditional expectations in the textbook Clark--Ocone identity. The Brownian
coordinate directions are total in the Cameron--Martin space, so the displayed
generator law determines the continuous time realization. -/
theorem generated_clark_ocone
    {W : Type u} [NormedAddCommGroup W] [NormedSpace ℝ W]
    [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
    [SecondCountableTopology W]
    {P : Measure W} [IsGaussian P] {B : ℝ≥0 → W → ℝ}
    (hB : IsPreBrownianReal B P)
    (coordinate : ℝ≥0 → StrongDual ℝ W)
    (coordinate_apply : ∀ t w, B t w = coordinate t w)
    (generated : IsWienerGenerated B)
    (hsm : ∀ t, StronglyMeasurable (B t))
    {filtration : Filtration ℝ≥0 ‹MeasurableSpace W›}
    (hnat : filtration = Filtration.natural B hsm) :
    ∃ (timeDerivative : Lp (CameronMartin.Space P) 2 P →ₗᵢ[ℝ] TimeProcessL2 P)
        (itoIntegral : PredictableProcessL2 filtration P →L[ℝ] RandomL2 P),
      (∀ h : CameronMartin.Space P,
        (∀ t, ⟪h, CameronMartin.ofDual P (coordinate t)⟫_ℝ = 0) → h = 0) ∧
      (∀ t (G : RandomL2 P),
        (timeDerivative (smulLp (CameronMartin.ofDual P (coordinate t)) G) :
            ℝ≥0 × W → ℝ) =ᵐ[nonnegativeLebesgueMeasure.prod P]
          fun p ↦ (Set.Ioc 0 t).indicator (1 : ℝ≥0 → ℝ) p.1 * G p.2) ∧
      (∀ U, ‖itoIntegral U‖ = ‖U‖) ∧
      (∀ U, ∫ w, itoIntegral U w ∂P = 0) ∧
      (∀ {a b : ℝ≥0} (_hab : a ≤ b)
          (Z : lpMeas ℝ ℝ (filtration a) 2 P),
        ∃ U : PredictableProcessL2 filtration P,
          (U : ℝ≥0 × W → ℝ) =ᵐ[nonnegativeLebesgueMeasure.prod P]
            (fun p ↦ (Set.Ioc a b).indicator (1 : ℝ≥0 → ℝ) p.1 *
              (Z : W → ℝ) p.2) ∧
          (itoIntegral U : W → ℝ) =ᵐ[P]
            fun w ↦ (Z : W → ℝ) w * (B b w - B a w)) ∧
      (∀ G : RandomL2 P, ∃ U : PredictableProcessL2 filtration P,
        G = expectationL2 G + itoIntegral U) ∧
      ∀ {F : RandomL2 P} {η : Lp (CameronMartin.Space P) 2 P},
        InGraphClosure P F η →
          ∃ G : ℝ≥0 × W → ℝ,
            StronglyMeasurable[filtration.predictable] G ∧
            (predictableProjection filtration (timeDerivative η) :
                ℝ≥0 × W → ℝ) =ᵐ[nonnegativeLebesgueMeasure.prod P] G ∧
            (∀ᵐ t ∂nonnegativeLebesgueMeasure, 0 < t →
              (fun w ↦ G (t, w)) =ᵐ[P]
                P[(fun w ↦ (timeDerivative η : ℝ≥0 × W → ℝ) (t, w)) |
                  filtration t]) ∧
            F = expectationL2 F +
              itoIntegral (predictableProjection filtration (timeDerivative η)) := sorry

end PalomarClarkOcone
