/-
Copyright (c) 2026 The lean-malliavin contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The lean-malliavin contributors
-/
import Malliavin.NaturalItoDuality
import Mathlib.Probability.Kernel.Condexp

/-!
# From timewise conditional expectations to the predictable projection

For a product-`L²` process `U`, Mathlib's fixed-time regular conditional kernels give the
pointwise candidate

`(t, ω) ↦ ∫ ω', U (t, ω') ∂condExpKernel P (𝓕 t) ω`.

This file proves a uniqueness bridge: any predictable product-`L²` process whose sections are
almost everywhere the fixed-time conditional expectations must equal `predictableProjection 𝓕 U`.
Consequently, if the displayed kernel candidate is jointly predictably measurable, fixed-time
`L²` contraction implies that it belongs to product `L²`, and it represents the product-space
predictable projection.

Joint predictability is a sufficient condition, but it is not proved here for the natural
Brownian filtration.  In particular, the results below do not erase the remaining regularity gap
between a family of fixed-time conditional expectations and a jointly predictable process.  For
a general filtration this issue is substantive at filtration jumps: the predictable
σ-algebra is generated by strictly prior events, while the candidate conditions on `𝓕 t`.  No
left-continuity or usual-augmentation result for the natural filtration is assumed here.
-/

open MeasureTheory ProbabilityTheory Filter
open scoped ENNReal NNReal InnerProductSpace

noncomputable section

namespace Malliavin

variable {W : Type*} [NormedAddCommGroup W] [NormedSpace ℝ W]
  [CompleteSpace W] [MeasurableSpace W] [BorelSpace W]
  [SecondCountableTopology W]
  {P : Measure W} [IsGaussian P]

/-- The pointwise family obtained by applying the fixed-time conditional-expectation kernel to
the time section of a product-`L²` process.

No joint measurability or product integrability is built into this definition. -/
noncomputable def timewiseCondExpKernelRepresentative
    (𝓕 : Filtration ℝ≥0 ‹MeasurableSpace W›) (U : TimeProcessL2 P) :
    ℝ≥0 × W → ℝ :=
  fun z ↦ ∫ w', U (z.1, w') ∂condExpKernel P (𝓕 z.1) z.2

omit [CompleteSpace W] [BorelSpace W] in
private lemma setIntegral_timewiseCondExp_Ioc
    (𝓕 : Filtration ℝ≥0 ‹MeasurableSpace W›)
    (U : TimeProcessL2 P) (V : PredictableProcessL2 𝓕 P)
    (hV : ∀ᵐ t ∂nonnegativeLebesgueMeasure,
      (fun w ↦ (V : ℝ≥0 × W → ℝ) (t, w)) =ᵐ[P]
        P[(fun w ↦ U (t, w)) | 𝓕 t])
    (a b : ℝ≥0) {A : Set W} (hA : MeasurableSet[𝓕 a] A) :
    ∫ t in Set.Ioc a b, ∫ w in A,
        (V : ℝ≥0 × W → ℝ) (t, w) ∂P ∂nonnegativeLebesgueMeasure =
      ∫ t in Set.Ioc a b, ∫ w in A,
        U (t, w) ∂P ∂nonnegativeLebesgueMeasure := by
  have hsec := memLp_timeSection_ae U
  apply integral_congr_ae
  filter_upwards [ae_restrict_le hV, ae_restrict_le hsec,
    ae_restrict_mem measurableSet_Ioc] with t hVt hUt ht
  have hUint : Integrable (fun w ↦ U (t, w)) P :=
    hUt.integrable one_le_two
  calc
    ∫ w in A, (V : ℝ≥0 × W → ℝ) (t, w) ∂P =
        ∫ w in A, P[(fun w ↦ U (t, w)) | 𝓕 t] w ∂P :=
      integral_congr_ae (ae_restrict_le hVt)
    _ = ∫ w in A, U (t, w) ∂P :=
      setIntegral_condExp (𝓕.le t) hUint (𝓕.mono ht.1.le A hA)

omit [CompleteSpace W] [BorelSpace W] in
/-- A predictable product-`L²` version of the fixed-time conditional expectations is
necessarily the product-space predictable projection. -/
theorem predictableProjection_eq_of_ae_timewiseCondExp
    (𝓕 : Filtration ℝ≥0 ‹MeasurableSpace W›)
    (U : TimeProcessL2 P) (V : PredictableProcessL2 𝓕 P)
    (hV : ∀ᵐ t ∂nonnegativeLebesgueMeasure,
      (fun w ↦ (V : ℝ≥0 × W → ℝ) (t, w)) =ᵐ[P]
        P[(fun w ↦ U (t, w)) | 𝓕 t]) :
    predictableProjection 𝓕 U = V := by
  let Q := predictableProjection 𝓕 U
  let g : PredictableProcessL2 𝓕 P := Q - V
  have hrect : ∀ R ∈ predictableRectangle 𝓕,
      ∫ z in R, (g : ℝ≥0 × W → ℝ) z
        ∂nonnegativeLebesgueMeasure.prod P = 0 := by
    intro R hR
    rcases hR with ⟨F₀, _hF₀, rfl⟩ | ⟨a, b, A, _hab, hA, rfl⟩
    · apply setIntegral_measure_zero
      rw [Measure.prod_prod, measure_singleton, zero_mul]
    · have hμrect : (nonnegativeLebesgueMeasure.prod P)
          (Set.Ioc a b ×ˢ A) ≠ ∞ := by
        rw [Measure.prod_prod]
        exact ENNReal.mul_ne_top
          (nonnegativeLebesgueMeasure_Ioc_ne_top a b) (measure_ne_top P A)
      have hQint : IntegrableOn
          (Q : ℝ≥0 × W → ℝ) (Set.Ioc a b ×ˢ A)
          (nonnegativeLebesgueMeasure.prod P) :=
        integrableOn_Lp_of_measure_ne_top (Q : TimeProcessL2 P)
          one_le_two hμrect
      have hVint : IntegrableOn
          (V : ℝ≥0 × W → ℝ) (Set.Ioc a b ×ˢ A)
          (nonnegativeLebesgueMeasure.prod P) :=
        integrableOn_Lp_of_measure_ne_top (V : TimeProcessL2 P)
          one_le_two hμrect
      have hcoe : (g : ℝ≥0 × W → ℝ) =ᵐ[
          nonnegativeLebesgueMeasure.prod P]
          fun z ↦ (Q : ℝ≥0 × W → ℝ) z -
            (V : ℝ≥0 × W → ℝ) z := by
        have hgLp : (g : TimeProcessL2 P) =
            (Q : TimeProcessL2 P) - (V : TimeProcessL2 P) := rfl
        rw [hgLp]
        exact Lp.coeFn_sub (Q : TimeProcessL2 P) (V : TimeProcessL2 P)
      calc
        ∫ z in Set.Ioc a b ×ˢ A, (g : ℝ≥0 × W → ℝ) z
            ∂nonnegativeLebesgueMeasure.prod P =
            ∫ z in Set.Ioc a b ×ˢ A,
              ((Q : ℝ≥0 × W → ℝ) z -
                (V : ℝ≥0 × W → ℝ) z)
              ∂nonnegativeLebesgueMeasure.prod P :=
          integral_congr_ae (ae_restrict_le hcoe)
        _ = (∫ z in Set.Ioc a b ×ˢ A,
              (Q : ℝ≥0 × W → ℝ) z
              ∂nonnegativeLebesgueMeasure.prod P) -
            ∫ z in Set.Ioc a b ×ˢ A,
              (V : ℝ≥0 × W → ℝ) z
              ∂nonnegativeLebesgueMeasure.prod P :=
          integral_sub' hQint hVint
        _ = 0 := by
          rw [setIntegral_prod _ hQint, setIntegral_prod _ hVint,
            integral_predictableProjection_Ioc 𝓕 U a b hA,
            setIntegral_timewiseCondExp_Ioc 𝓕 U V hV a b hA,
            sub_self]
  have hg0 : (g : ℝ≥0 × W → ℝ) =ᵐ[
      nonnegativeLebesgueMeasure.prod P] 0 := by
    apply lpMeas.ae_eq_zero_of_forall_setIntegral_eq_zero
      (predictable_le_prod 𝓕) g (by norm_num) (by norm_num)
    · intro s _hs hμs
      exact integrableOn_Lp_of_measure_ne_top
        (g : TimeProcessL2 P) one_le_two hμs.ne
    · intro s hs hμs
      exact integral_set_eq_zero_of_rectangles 𝓕 g hrect s hs hμs
  have hg : g = 0 := by
    apply Subtype.ext
    apply Lp.ext
    exact hg0.trans (Lp.coeFn_zero ℝ 2
      (nonnegativeLebesgueMeasure.prod P)).symm
  exact sub_eq_zero.mp hg

/-- Kernel form of `predictableProjection_eq_of_ae_timewiseCondExp`.  The usual Malliavin
assumptions infer that `W` is standard Borel and that `P` is finite. -/
theorem predictableProjection_eq_of_ae_timewiseCondExpKernel
    (𝓕 : Filtration ℝ≥0 ‹MeasurableSpace W›)
    (U : TimeProcessL2 P) (V : PredictableProcessL2 𝓕 P)
    (hV : ∀ᵐ t ∂nonnegativeLebesgueMeasure,
      (fun w ↦ (V : ℝ≥0 × W → ℝ) (t, w)) =ᵐ[P]
        fun w ↦ ∫ w', U (t, w') ∂condExpKernel P (𝓕 t) w) :
    predictableProjection 𝓕 U = V := by
  apply predictableProjection_eq_of_ae_timewiseCondExp 𝓕 U V
  filter_upwards [hV, memLp_timeSection_ae U] with t hVt hUt
  have hUint : Integrable (fun w ↦ U (t, w)) P :=
    hUt.integrable one_le_two
  exact hVt.trans
    (condExp_ae_eq_integral_condExpKernel (𝓕.le t) hUint).symm

/-- Joint predictable measurability of the timewise conditional-kernel candidate implies its
product-`L²` integrability.  The proof integrates the fixed-time `L²` contraction for conditional
expectation over time. -/
theorem memLp_timewiseCondExpKernelRepresentative
    (𝓕 : Filtration ℝ≥0 ‹MeasurableSpace W›) (U : TimeProcessL2 P)
    (hpred : AEStronglyMeasurable[𝓕.predictable]
      (timewiseCondExpKernelRepresentative 𝓕 U)
      (nonnegativeLebesgueMeasure.prod P)) :
    MemLp (timewiseCondExpKernelRepresentative 𝓕 U) 2
      (nonnegativeLebesgueMeasure.prod P) := by
  let C := timewiseCondExpKernelRepresentative 𝓕 U
  have hCmeas : AEStronglyMeasurable C
      (nonnegativeLebesgueMeasure.prod P) :=
    hpred.mono (predictable_le_prod 𝓕)
  apply (memLp_two_iff_integrable_sq hCmeas).2
  have hCsqMeas : AEStronglyMeasurable (fun z ↦ C z ^ 2)
      (nonnegativeLebesgueMeasure.prod P) := hCmeas.pow 2
  apply (integrable_prod_iff hCsqMeas).2
  constructor
  · filter_upwards [memLp_timeSection_ae U] with t hUt
    have hCE : (fun w ↦ C (t, w)) =ᵐ[P]
        P[(fun w ↦ U (t, w)) | 𝓕 t] := by
      exact (condExp_ae_eq_integral_condExpKernel (𝓕.le t)
        (hUt.integrable one_le_two)).symm
    exact ((memLp_congr_ae hCE).2 (hUt.condExp one_le_two)).integrable_sq
  · have hUOuter : Integrable
        (fun t ↦ ∫ w, ‖(U (t, w)) ^ 2‖ ∂P)
        nonnegativeLebesgueMeasure :=
      (Lp.memLp U).integrable_sq.integral_norm_prod_left
    have hCOuterMeas : AEStronglyMeasurable
        (fun t ↦ ∫ w, ‖C (t, w) ^ 2‖ ∂P)
        nonnegativeLebesgueMeasure := hCsqMeas.norm.integral_prod_right'
    apply hUOuter.mono' hCOuterMeas
    filter_upwards [memLp_timeSection_ae U] with t hUt
    have hCE : (fun w ↦ C (t, w)) =ᵐ[P]
        P[(fun w ↦ U (t, w)) | 𝓕 t] := by
      exact (condExp_ae_eq_integral_condExpKernel (𝓕.le t)
        (hUt.integrable one_le_two)).symm
    have hEq : (∫ w, ‖C (t, w) ^ 2‖ ∂P) =
        ∫ w, ‖P[(fun w ↦ U (t, w)) | 𝓕 t] w‖ ^ 2 ∂P := by
      apply integral_congr_ae
      filter_upwards [hCE] with w hw
      rw [hw, norm_pow]
    rw [Real.norm_eq_abs,
      abs_of_nonneg (integral_nonneg fun _ ↦ norm_nonneg _), hEq]
    have hUnormSq : Integrable (fun w ↦ ‖U (t, w)‖ ^ 2) P := by
      simpa only [norm_pow] using hUt.integrable_sq.norm
    simpa only [Real.rpow_two, norm_pow] using
      integral_norm_condExp_rpow_le (m := 𝓕 t) (p := (2 : ℝ)) one_le_two
        (by simpa only [Real.rpow_two] using hUnormSq)

/-- If the pointwise timewise-kernel candidate is jointly predictably measurable, then it is a
representative of the product-space predictable projection.  Its product-`L²` bound follows from
`memLp_timewiseCondExpKernelRepresentative`.

Joint predictability is not established here for the natural Brownian filtration. -/
theorem predictableProjection_ae_eq_timewiseCondExpKernel
    (𝓕 : Filtration ℝ≥0 ‹MeasurableSpace W›) (U : TimeProcessL2 P)
    (hpred : AEStronglyMeasurable[𝓕.predictable]
      (timewiseCondExpKernelRepresentative 𝓕 U)
      (nonnegativeLebesgueMeasure.prod P)) :
    (predictableProjection 𝓕 U : ℝ≥0 × W → ℝ) =ᵐ[
      nonnegativeLebesgueMeasure.prod P]
        timewiseCondExpKernelRepresentative 𝓕 U := by
  have hL2 := memLp_timewiseCondExpKernelRepresentative 𝓕 U hpred
  let V : PredictableProcessL2 𝓕 P :=
    ⟨hL2.toLp (timewiseCondExpKernelRepresentative 𝓕 U),
      hpred.congr hL2.coeFn_toLp.symm⟩
  have hV : ∀ᵐ t ∂nonnegativeLebesgueMeasure,
      (fun w ↦ (V : ℝ≥0 × W → ℝ) (t, w)) =ᵐ[P]
        fun w ↦ ∫ w', U (t, w') ∂condExpKernel P (𝓕 t) w := by
    filter_upwards [Measure.ae_ae_of_ae_prod hL2.coeFn_toLp] with t ht
    filter_upwards [ht] with w hw
    simpa only [V, timewiseCondExpKernelRepresentative] using hw
  rw [predictableProjection_eq_of_ae_timewiseCondExpKernel 𝓕 U V hV]
  exact hL2.coeFn_toLp

section NaturalClarkOcone

variable {B : ℝ≥0 → W → ℝ}

/-- A timewise fixed-time-kernel identification of the canonical inverse-Itô integrand implies
the best-integrand equality used by the concrete Clark--Ocone constructor.

The timewise identification is an explicit hypothesis; this theorem does not prove its joint
regularity for the natural Brownian filtration. -/
theorem bestNaturalItoIntegrand_eq_predictableProjection_of_ae_timewiseCondExpKernel
    (hB : IsPreBrownianReal B P) (coordinate : ℝ≥0 → StrongDual ℝ W)
    (coordinate_apply : ∀ t w, B t w = coordinate t w)
    (generated : IsWienerGenerated B)
    (hsm : ∀ t, StronglyMeasurable (B t))
    {𝓅 : Filtration ℝ≥0 ‹MeasurableSpace W›}
    (hnat : 𝓅 = Filtration.natural B hsm) (F : D12 P)
    (hTimewise : ∀ᵐ t ∂nonnegativeLebesgueMeasure,
      (fun w ↦
        (bestNaturalItoIntegrand hB hsm hnat (centeredPartL2 F.1) :
          ℝ≥0 × W → ℝ) (t, w)) =ᵐ[P]
        fun w ↦ ∫ w',
          (Malliavin.timeDerivative hB coordinate coordinate_apply generated
            (mderivD12 P F) : ℝ≥0 × W → ℝ) (t, w')
          ∂condExpKernel P (𝓅 t) w) :
    bestNaturalItoIntegrand hB hsm hnat (centeredPartL2 F.1) =
      predictableProjection 𝓅
        (Malliavin.timeDerivative hB coordinate coordinate_apply generated
          (mderivD12 P F)) :=
  (predictableProjection_eq_of_ae_timewiseCondExpKernel 𝓅
    (Malliavin.timeDerivative hB coordinate coordinate_apply generated
      (mderivD12 P F))
    (bestNaturalItoIntegrand hB hsm hnat (centeredPartL2 F.1)) hTimewise).symm

/-- Construct a `ClarkOconeFamily` from martingale representation and the textbook timewise
conditional-kernel formula for every Malliavin derivative.

This constructor remains conditional: it does not establish the assumed almost-every-time
section formula for the natural Brownian filtration.  That formula is stronger than the bare
existence of each fixed-time kernel, since the chosen best integrand supplies a jointly
predictable product-`L²` version. -/
noncomputable def ClarkOconeFamily.ofNaturalItoTimewiseCondExpKernel
    (hB : IsPreBrownianReal B P) (coordinate : ℝ≥0 → StrongDual ℝ W)
    (coordinate_apply : ∀ t w, B t w = coordinate t w)
    (generated : IsWienerGenerated B)
    (hsm : ∀ t, StronglyMeasurable (B t))
    {𝓅 : Filtration ℝ≥0 ‹MeasurableSpace W›}
    (hnat : 𝓅 = Filtration.natural B hsm)
    (hMRT : NaturalMartingaleRepresentation hB hsm hnat)
    (hTimewise : ∀ F : D12 P,
      ∀ᵐ t ∂nonnegativeLebesgueMeasure,
        (fun w ↦
          (bestNaturalItoIntegrand hB hsm hnat (centeredPartL2 F.1) :
            ℝ≥0 × W → ℝ) (t, w)) =ᵐ[P]
          fun w ↦ ∫ w',
            (Malliavin.timeDerivative hB coordinate coordinate_apply generated
              (mderivD12 P F) : ℝ≥0 × W → ℝ) (t, w')
            ∂condExpKernel P (𝓅 t) w) :
    ClarkOconeFamily B P 𝓅 :=
  ClarkOconeFamily.ofNaturalItoBestIntegrand hB coordinate coordinate_apply
    generated hsm hnat hMRT fun F ↦
      bestNaturalItoIntegrand_eq_predictableProjection_of_ae_timewiseCondExpKernel
        hB coordinate coordinate_apply generated hsm hnat F (hTimewise F)

end NaturalClarkOcone

end Malliavin
